version: "3"
services:
  pygeoapi:
    image: epinux/sat_pygeoapi
    build: .
    environment:
      DEBUG: 1
      PYTHONUNBUFFERED: 1
      LOGLEVEL: DEBUG
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
    ports:
      - 80:80
      - 5000:5000
    hostname: pygeoapi
    volumes:
      - ./start_pygeoapi.sh:/start_pygeoapi.sh
      - './noaa19-avhrr-20230124115334-20230124120327.nc:/pygeoapi/noaa19-avhrr-20230124115334-20230124120327.nc'
    entrypoint: /start_pygeoapi.sh
    depends_on:
      - celery
      - redis
    networks:
      - net

  celery:
    image: epinux/sat_pygeoapi
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
      PYTHONUNBUFFERED: 1
    volumes:
      - ./start_celery.sh:/start_celery.sh
      - './noaa19-avhrr-20230124115334-20230124120327.nc:/pygeoapi/noaa19-avhrr-20230124115334-20230124120327.nc'
    entrypoint: /start_celery.sh
    depends_on:
      - redis
    hostname: celery
    networks:
      - net

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379
    networks:
      - net

networks:
  net:
    attachable: true
  vpn-friendly:
    external: true
